version: 2
updates:
  # npm for JavaScript client
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    target-branch: "web-app"
    labels:
      - "npm dependencies"

  # pip for Python backend
  - package-ecosystem: "pip"
    directory: "/"  # root of the web-app branch
    schedule:
      interval: "weekly"
    target-branch: "web-app"
    labels:
      - "pip dependencies"
