default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
    exclude: ^tools/(yolo/(YOLOv6|ultralytics|yolov5)|yolov6r1/YOLOv6R1|yolov6r3/(Efficient-Computing|YOLOv6R3)|yolov7/yolov7)/

  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        language: python
        types: [python]
        additional_dependencies: [docformatter==1.7.5, tomli]
        args: [--in-place, --black, --style=epytext]
        exclude: ^tools/(yolo/(YOLOv6|ultralytics|yolov5)|yolov6r1/YOLOv6R1|yolov6r3/(Efficient-Computing|YOLOv6R3)|yolov7/yolov7)/

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.10
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-gfm==0.3.6]
    exclude: ^tools/(yolo/(YOLOv6|ultralytics|yolov5)|yolov6r1/YOLOv6R1|yolov6r3/(Efficient-Computing|YOLOv6R3)|yolov7/yolov7)/

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
    exclude: ^tools/(yolo/(YOLOv6|ultralytics|yolov5)|yolov6r1/YOLOv6R1|yolov6r3/(Efficient-Computing|YOLOv6R3)|yolov7/yolov7)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-toml
      - id: no-commit-to-branch
        args: [--branch, main]
    exclude: ^tools/(yolo/(YOLOv6|ultralytics|yolov5)|yolov6r1/YOLOv6R1|yolov6r3/(Efficient-Computing|YOLOv6R3)|yolov7/yolov7)/
