STATUS_OK = 200
OUTPUT_FILE_NAME = "output.zip"
# DEFAULT_URL = "https://tools.luxonis.com"
DEFAULT_NSHAVES = 6
DEFAULT_USE_LEGACY_FRONTEND = "true"
DEFAULT_USE_RVC2 = "true"


V5_SOURCE_FOLDER: str = "./weights/"
V6R1_SOURCE_FOLDER: str = "./weights/"
V6R2_SOURCE_FOLDER: str = "./weights/"
V6R21_SOURCE_FOLDER: str = "./weights/"
V6R3_SOURCE_FOLDER: str = "./weights/"
V6R4_SOURCE_FOLDER: str = "./weights/"
V7_SOURCE_FOLDER: str = "./weights/"
V8_SOURCE_FOLDER: str = "./weights/"
V9_SOURCE_FOLDER: str = "./weights/"
V10_SOURCE_FOLDER: str = "./weights/"
V11_SOURCE_FOLDER: str = "./weights/"

URL_V7: str = "/yolov7"
URL_V6R3: str = "/yolov6r3"
URL_V6R1: str = "/yolov6r1"

TEST_MODELS = [
    {
        "name": "yolov3-tinyu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6nr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6sr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6nr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6tr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6sr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6nr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6sr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6nr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6sr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6nr1",
        "version": "v6",
        "folder": V6R1_SOURCE_FOLDER,
        "url_suffix": URL_V6R1,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6tr1",
        "version": "v6",
        "folder": V6R1_SOURCE_FOLDER,
        "url_suffix": URL_V6R1,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5n",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5s",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5n6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5s6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5m6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5l6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov8n",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5nu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5n6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5s6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5su",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5m6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5mu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5l6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5lu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov8s",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov9t",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov9s",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov9m",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov9c",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov9e",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov7t",
        "version": "v7",
        "folder": V7_SOURCE_FOLDER,
        "url_suffix": URL_V7,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6mr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6mr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6mr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6mr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6lr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6lr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6lr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6lr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov6sr1",
        "version": "v6",
        "folder": V6R1_SOURCE_FOLDER,
        "url_suffix": URL_V6R1,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5m",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov8m",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5l",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov5x",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov8l",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov8x",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov7",
        "version": "v7",
        "folder": V7_SOURCE_FOLDER,
        "url_suffix": URL_V7,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov7x",
        "version": "v7",
        "folder": V7_SOURCE_FOLDER,
        "url_suffix": URL_V7,
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov10n",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov10s",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov10m",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov10b",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov10l",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov10x",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov11n",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov11s",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov11m",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov11l",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov11x",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": True,
    },
    {
        "name": "yolov3-tinyu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6nr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6sr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6nr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6tr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6sr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6nr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6sr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6nr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6sr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6nr1",
        "version": "v6",
        "folder": V6R1_SOURCE_FOLDER,
        "url_suffix": URL_V6R1,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6tr1",
        "version": "v6",
        "folder": V6R1_SOURCE_FOLDER,
        "url_suffix": URL_V6R1,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5n",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5s",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5n6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5s6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5m6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5l6",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov8n",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5nu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5n6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5s6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5su",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5m6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5mu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5l6u",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5lu",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov8s",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov9t",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov9s",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov9m",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov9c",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov9e",
        "version": "v9",
        "folder": V9_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov7t",
        "version": "v7",
        "folder": V7_SOURCE_FOLDER,
        "url_suffix": URL_V7,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6mr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6mr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6mr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6mr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6lr4",
        "version": "v6r4",
        "folder": V6R4_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6lr2",
        "version": "v6r2",
        "folder": V6R2_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6lr21",
        "version": "v6r2",
        "folder": V6R21_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6lr3",
        "version": "v6r2",
        "folder": V6R3_SOURCE_FOLDER,
        "url_suffix": URL_V6R3,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov6sr1",
        "version": "v6",
        "folder": V6R1_SOURCE_FOLDER,
        "url_suffix": URL_V6R1,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5m",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov8m",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5l",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov5x",
        "version": "v5",
        "folder": V5_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov8l",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov8x",
        "version": "v8",
        "folder": V8_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov7",
        "version": "v7",
        "folder": V7_SOURCE_FOLDER,
        "url_suffix": URL_V7,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov7x",
        "version": "v7",
        "folder": V7_SOURCE_FOLDER,
        "url_suffix": URL_V7,
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov10n",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov10s",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov10m",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov10b",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov10l",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov10x",
        "version": "v10",
        "folder": V10_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov11n",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov11s",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov11m",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov11l",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
    {
        "name": "yolov11x",
        "version": "v11",
        "folder": V11_SOURCE_FOLDER,
        "url_suffix": "",
        "shape": 320,
        "use_rvc2": False,
    },
]


MODEL_TYPE2URL: dict[str, str] = {
    "yolov3-tinyu": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov3-tinyu.pt",
    "yolov6nr4": "https://github.com/meituan/YOLOv6/releases/download/0.4.0/yolov6n.pt",
    "yolov6sr4": "https://github.com/meituan/YOLOv6/releases/download/0.4.0/yolov6s.pt",
    "yolov6nr2": "https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6n.pt",
    "yolov6tr2": "https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6t.pt",
    "yolov6sr2": "https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6s.pt",
    "yolov6nr21": "https://github.com/meituan/YOLOv6/releases/download/0.2.1/yolov6n_base.pt",
    "yolov6sr21": "https://github.com/meituan/YOLOv6/releases/download/0.2.1/yolov6s_base.pt",
    "yolov6nr3": "https://github.com/meituan/YOLOv6/releases/download/0.3.0/yolov6n.pt",
    "yolov6sr3": "https://github.com/meituan/YOLOv6/releases/download/0.3.0/yolov6s.pt",
    "yolov6nr1": "https://github.com/meituan/YOLOv6/releases/download/0.1.0/yolov6n.pt",
    "yolov6tr1": "https://github.com/meituan/YOLOv6/releases/download/0.1.0/yolov6t.pt",
    "yolov5n": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5n.pt",
    "yolov5s": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt",
    "yolov5m": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5m.pt",
    "yolov5l": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5l.pt",
    "yolov5n6": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5n6.pt",
    "yolov5s6": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s6.pt",
    "yolov5m6": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5m6.pt",
    "yolov5l6": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5l6.pt",
    "yolov5x": "https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5x.pt",
    "yolov5nu": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5nu.pt",
    "yolov5su": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5su.pt",
    "yolov5mu": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5mu.pt",
    "yolov5lu": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5lu.pt",
    "yolov5n6u": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5n6u.pt",
    "yolov5s6u": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5s6u.pt",
    "yolov5m6u": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5m6u.pt",
    "yolov5l6u": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov5l6u.pt",
    "yolov6mr4": "https://github.com/meituan/YOLOv6/releases/download/0.4.0/yolov6m.pt",
    "yolov6lr4": "https://github.com/meituan/YOLOv6/releases/download/0.4.0/yolov6l.pt",
    "yolov6mr2": "https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6m.pt",
    "yolov6lr2": "https://github.com/meituan/YOLOv6/releases/download/0.2.0/yolov6l.pt",
    "yolov6mr21": "https://github.com/meituan/YOLOv6/releases/download/0.2.1/yolov6m_base.pt",
    "yolov6lr21": "https://github.com/meituan/YOLOv6/releases/download/0.2.1/yolov6l_base.pt",
    "yolov6mr3": "https://github.com/meituan/YOLOv6/releases/download/0.3.0/yolov6m.pt",
    "yolov6lr3": "https://github.com/meituan/YOLOv6/releases/download/0.3.0/yolov6l.pt",
    "yolov6sr1": "https://github.com/meituan/YOLOv6/releases/download/0.1.0/yolov6s.pt",
    "yolov7t": "https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt",
    "yolov7": "https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt",
    "yolov7x": "https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7x.pt",
    "yolov8n": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt",
    "yolov8s": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8s.pt",
    "yolov8m": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt",
    "yolov8l": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8l.pt",
    "yolov8x": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8x.pt",
    "yolov9t": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov9t.pt",
    "yolov9s": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov9s.pt",
    "yolov9m": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov9m.pt",
    "yolov9c": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov9c.pt",
    "yolov9e": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov9e.pt",
    "yolov10n": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10n.pt",
    "yolov10s": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10s.pt",
    "yolov10m": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10m.pt",
    "yolov10b": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10b.pt",
    "yolov10l": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10l.pt",
    "yolov10x": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov10x.pt",
    "yolov11n": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt",
    "yolov11s": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s.pt",
    "yolov11m": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11m.pt",
    "yolov11l": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11l.pt",
    "yolov11x": "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11x.pt",
}
